services:
  - type: web
    name: portfolio
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn portfolio.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio.settings
